#General Settings
lisence_key: "" # Set Lisence key which provided by sparkle
vcc_use: 4 # How many Times to use 1 VCC, I reccomend 4 - 100% Success Rate
proxyless: false # Set True if you dont have proxies
dated_output: True # Make a different folder for each session
smart_sleep: 5 # Sleep Redeemer after Redeem Token in seconds
Vcc_Authenticator: true # Authenticate Vccs
Remove_vcc_after_Redeem: True # Removes Card after 

#Password Settings
Password_Changer: true # true for enable false for disable
custom: true
Password: ""

#Request Retries
Request_Retries: 5

#Auth Retries
Authentication_Reties: 5

Webhook:
  Webhook_Logging: true
  webhook_url: "" # Webhook Url
  Arrow_Emojis_ID: "<a:Arrow:1202258147650314270>" # Arrow Emoji ID for Embed

Captcha:
  Solvercaptcha: false # Enable if you want to Tacle Captcha
  use_proxies: false # Enable if you want Fast and Good Captcha Solves
  service: "capsolver.com" # hcoptcha.online, capsolver.com
  key: "" # hcoptcha.com Api key
  failed_retries: 2

Customization:
  Customize: false # Sets it true for customization
  global_name: "adarshgay" # gets global name
  bio: ".gg/hideouts ontop" # Changes bio

custom_billing:
  use_custom_bill: True # I reccomend to set on False Unless you know what you are doing!
  person_name: "uk"
  address_2: "uk"
  country: "GB"  # United KingDom Is GB
  address: "uk"
  postal: "LU3 1NZ"
  state: "uk"
  city: "uk"